version: '3.1'
services:
  nginx-master:
    image: nginx
    container_name: nginx-master
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /www/wwwroot/master:/usr/local/nginx/html/:rw
      - ./conf/nginx/nginx_80/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx_80/ssl:/etc/nginx/cetr/:ro
      - ./conf/nginx/nginx_80/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/nginx_80/:/var/log/nginx/:rw
    networks:
      - front

  nginx-slave1:
    image: nginx
    container_name: nginx-slave1
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "81:80"
    volumes:
      - /www/wwwroot/slave1:/usr/local/nginx/html/:rw
      - ./conf/nginx/nginx_81/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx_81/ssl:/etc/nginx/cetr/:ro
      - ./conf/nginx/nginx_81/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/nginx_81/:/var/log/nginx/:rw
    networks:
      - front

  nginx-slave2:
    image: nginx
    container_name: nginx-slave2
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "82:80"
    volumes:
      - /www/wwwroot/slave2:/usr/local/nginx/html/:rw
      - ./conf/nginx/nginx_82/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx_82/ssl:/etc/nginx/cetr/:ro
      - ./conf/nginx/nginx_82/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/nginx_82/:/var/log/nginx/:rw
    networks:
      - front

  phpfpm:
    image: raven666/ct-phpfpm:latest
    container_name: my-phpfpm
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    expose:
      - "9000"
    volumes:
      - /www/wwwroot/master:/usr/local/nginx/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./conf/supervisor/conf.d:/etc/supervisor/conf.d/:ro
      - ./log/php-fpm/:/var/log/php-fpm/:rw
      - ./log/supervisor/:/var/log/supervisor/:rw
    command: supervisord -n
    networks:
      - front
      - backend

networks:
  front:
  backend:

